app.js, models/comments.js, models/index.js, models/likes.js, models/pharmacyLike.js, models/users.js
박대현:데이터베이스 모델 추가 10월 21일 오후 3시 39분
=> 박대현:데이터베이스 모델 추가 10월 21일 오후 3시 39분

models/Reviews.js, models/likes.js, models/users.js
박대현:데이터 베이스 모델 수정 10-21 오후 4시 25분
=> 박대현:데이터 베이스 모델 수정 10-21 오후 4시 25분

models/Reviews.js, models/index.js, models/likes.js, models/pharmacyLike.js, models/users.js
=> 박대현:DB 테이블 변경 10-21 오후 8시 21분

controller/users.controller.js, repository/users.repository.js, routes/users.js, service/users.service.js
=> 장민영:회원가입완료! 10월21일 23시57분

app.js, config/config.js, models/Reviews.js, models/index.js, models/likes.js, models/pharmacyLikes.js, models/users.js, package-lock.json, package.json, public_html/index.html
- 공공 API 불러오기 연습 중 10월 21일 20:37
- 네이버 지도 API 연습 10월 22일 01시 30분
- DB 스키마 수정 10월 22일 02시 09분
=> 백지영: 10월 22일 작업내역 반영 10월 22일 02시 12분

models/index.js, models/users.js
=> 장민영:젠더오류 주석처리 10월22일 02시23분

app.js, controller/pharmacy.controller.js, public_html/index.html, repository/users.repository.js, routes/index.js, routes/pharmacy.js, routes/pharms.js, service/pharmacy.service.js
백지영: getPharmacyList 작업 중 10월 22일 09시 21분
=> 백지영: getPharmacyList 작업 중 10월 22일 09시 21분

controller/users.controller.js, repository/users.repository.js, service/users.service.js
=> 장민영:로그인기능완료 10월22일 10시47분

controller/users.controller.js, routes/users.js
장민영: 회원정보수정,탈퇴 api수정 10월22일 14시45분
=> 장민영: 회원정보수정,탈퇴 api수정 10월22일 14시45분

app.js, package-lock.json, package.json
[백지영: 프론트-백 연결 테스트 전 cors 추가 10월 22일 18:44]
=> 백지영: 프론트-백 연결 테스트 전 cors 추가 10월 22일 18:44

controller/pharmacy.controller.js, controller/reviews.controller.js, middlewares/error-handler-middleware.js, models/likes.js, models/pharmacyLikes.js, public_html/index.html, routes/pharmacy.js, service/pharmacy.services.js
박대현: 에러 핸들러 추가 및 약국 상세조회 API 추가 10-22 오후 8시 57분
=> 박대현: 에러 핸들러 추가 및 약국 상세조회 API 추가 10-22 오후 8시 57분

controller/users.controller.js, repository/users.repository.js, routes/users.js, service/users.service.js
=> 장민영:회원정보조회 구현완료 10월22일 23시22분

controller/users.controller.js, repository/users.repository.js, service/users.service.js
=> 장민영:회원탈퇴구현완료 10월22일 23시57분

app.js, controller/users.controller.js, middlewares/auth-middleware.js
[백지영: dotenv.config 추가 10월 23일 00시 57분]
=> 백지영: dotenv.config 추가 10월 23일 00시 57분

controller/likes.controller.js, middlewares/auth-middleware.js, repository/likes.repository.js, routes/likes.js, routes/users.js, service/likes.service.js
[백지영: 약국 좋아요 API 구현 완료 10월 23일 19시 53분]
=> 백지영: 약국 좋아요 API 구현 완료 10월 23일 19시 53분

controller/pharmacy.controller.js, controller/reviews.controller.js, controller/users.controller.js, middlewares/error-handler-middleware.js, models/Reviews.js, models/likes.js, models/pharmacyLikes.js, public_html/index.html, repository/users.repository.js, routes/pharmacy.js, routes/users.js, service/pharmacy.services.js, service/reviews.services.js, service/users.service.js
[백지영: 작업내용 다시 살려왔습니다.. 10월 23일 20:15]
=> 백지영: 작업내용 다시 살려왔습니다.. 10월 23일 20:15

controller/users.controller.js, repository/users.repository.js, service/users.service.js
장민영: 아이디 중복확인구현완료 10월24일 17시32분
=> 장민영: 아이디 중복확인구현완료 10월24일 17시32분

controller/users.controller.js
장민영: 회원가입 Joi 검증기능 10월 24일 23시00분
=> 장민영: 회원가입 Joi 검증기능 10월 24일 23시00분

models/index.js, models/likes.js, models/pharmacyLikes.js
백지영: db model likes, pharmacyLikes 10월 25일 03시 11분
=> 백지영: db model likes, pharmacyLikes 10월 25일 03시 11분

controller/users.controller.js, package-lock.json, package.json, service/users.service.js
장민영:암호화 bcrypt 완료 10월25일 17시01분
=> 장민영:암호화 bcrypt 완료 10월25일 17시01분

app.js, controller/users.controller.js, package-lock.json, package.json, repository/users.repository.js, routes/pharmacy.js, service/users.service.js, swagger-output.json, swagger.js
[백지영: swagger 작성중, getPharmacyList post요청으로 변경 10월 25일 18시 27분]
=> 백지영: swagger 작성중, getPharmacyList post요청으로 변경 10월 25일 18시 27분

routes/pharmacy.js, service/pharmacy.service.js, swagger-output.json
- [백지영: getPharmacyList get 메소드로 변경 10월 25일 23시 24분]
- [백지영: getPharmacy 인자값 수정 10월 25일 23시 27분]
=> 백지영: getPharmacyList get 메소드로 변경 10월 25일 23시 24분

controller/pharmacy.controller.js, controller/users.controller.js, models/likes.js, models/pharmacyLikes.js, routes/pharmacy.js, service/pharmacy.service.js
[백지영: 약국 상세정보 조회 API 공공데이터 URL 수정 10월 26일 01시 45분]
=> 백지영: 약국 상세정보 조회 API 공공데이터 URL 수정 10월 26일 01시 45분

controller/pharmacy.controller.js, routes/pharmacy.js, service/pharmacy.service.js
[백지영: 약국 상세 조회 오류 수정 중 10월 26일 02시 49분]
=> 백지영: 약국 상세 조회 오류 수정 중 10월 26일 02시 49분

controller/pharmacy.controller.js, service/pharmacy.service.js
[백지영: 약국 상세 조회 API 제발 돼줄래...? 10월 26일 03시 16분]
=> 백지영: 약국 상세 조회 API 제발 돼줄래...? 10월 26일 03시 16분

routes/pharmacy.js
[백지영: pharmacy router 다시 수정 10월 26일 03시 47분]
=> 백지영: pharmacy router 다시 수정 10월 26일 03시 47분

controller/pharmacy.controller.js, routes/users.js, service/pharmacy.service.js
[백지영: 약국 상세조회 API 서비스키값 안받아도 되도록 변경 10월 26일 11시 4분]
=> 백지영: 약국 상세조회 API 서비스키값 안받아도 되도록 변경 10월 26일 11시 4분

controller/reviews.controller.js, repository/reviews.repository.js, routes/reviews.js, service/reviews.service.js
박대현: getAllReview 추가 10-26 오전 11시 20분
=> 박대현: getAllReview 추가 10-26 오전 11시 20분

repository/users.repository.js, service/users.service.js
[백지영: 로그인 API 수정 10월 26일 12시 23분]
=> 백지영: 로그인 API 수정 10월 26일 12시 23분

controller/reviews.controller.js, controller/users.controller.js, routes/users.js, service/users.service.js
[백지영: 중복 아이디 체크 API 구현 완료 10월 26일 16시 28분](https://github.com/chamchimayo/mini_pharmacy/commit/b6e41832384434bad4faf2f3c15cfdb4018d1754)
=> 백지영: 중복 아이디 체크 API 구현 완료 10월 26일 16시 28분

controller/users.controller.js, service/users.service.js
[백지영: 중복 ID 검사 API 에러메세지 수정 10월 26일 16:51]
=> 백지영: 중복 ID 검사 API 에러메세지 수정 10월 26일 16:51

controller/users.controller.js
[백지영: 중복 아이디 체크 res.send에서 res.json으로 변경 10월 26일 17시 7분]
=> 백지영: 중복 아이디 체크 res.send에서 res.json으로 변경 10월 26일 17시 7분

controller/users.controller.js, repository/users.repository.js, routes/users.js, service/users.service.js
[백지영: 유저 정보 보기 API 수정 10월 26일 17시 41분]
=> 백지영: 유저 정보 보기 API 수정 10월 26일 17시 41분

controller/users.controller.js, service/users.service.js
박대현: 유저아이디 중복검사 아키텍쳐 수정 10-26 오후 5시 45분
=> 박대현: 유저아이디 중복검사 아키텍쳐 수정 10-26 오후 5시 45분

repository/users.repository.js
=> 장민영: 깃병합 10월27일 11시 15분
